import type { PlaceApi } from '../api/places'

export const placeApiStub: PlaceApi = {
  async listJungGu() {
    return {
      items: [
        {
          contentId: '3012345',
          name: '도그라운지 성수',
          category: 'FOOD',
          categoryLabel: '반려견 동반 음식점',
          distanceMeters: 620,
          walkingMinutes: 9,
          summary: '전 구역 동반 · 목줄 필요',
          address: '서울 중구 을지로 100',
          telephone: '02-1234-5678',
          imageUrl: 'https://example.com/place.jpg',
          thumbnailUrl: null,
          copyrightType: null,
          latitude: 37.5652,
          longitude: 126.9992,
        },
        {
          contentId: '4012345',
          name: '멍커피 을지로',
          category: 'FOOD',
          categoryLabel: '반려견 동반 카페',
          distanceMeters: 740,
          walkingMinutes: 11,
          summary: '야외 좌석 동반 가능',
          address: '서울 중구 을지로 120',
          telephone: null,
          imageUrl: null,
          thumbnailUrl: null,
          copyrightType: null,
          latitude: 37.566,
          longitude: 126.998,
        },
      ],
      page: 1,
      size: 100,
      totalCount: 2,
    }
  },
  async detail(contentId) {
    return {
      contentId,
      name: '도그라운지 성수',
      category: 'FOOD',
      categoryLabel: '반려견 동반 음식점',
      address: '서울 중구 을지로 100',
      telephone: '02-1234-5678',
      homepageUrl: null,
      imageUrl: 'https://example.com/place.jpg',
      thumbnailUrl: null,
      copyrightType: null,
      latitude: 37.5652,
      longitude: 126.9992,
      overview: '반려견과 함께 식사할 수 있는 서울 중구 음식점입니다.',
      food: {
        openingHours: '영업 중 · 21:00 영업 종료',
        restDate: null,
        mainMenu: null,
        menu: null,
        menuItems: [
          { name: '반려견 동반 브런치', price: 18000, specialty: true, imageUrl: 'https://example.com/menu.jpg' },
          { name: '아메리카노', price: 5000, specialty: false, imageUrl: null },
        ],
        menuSource: '매장 공개 메뉴',
        parking: null,
        packing: null,
        reservation: null,
        creditCard: null,
      },
      pet: {
        accompanimentType: '실내 전 구역 동반 가능',
        allowedAnimals: null,
        requirements: '목줄 착용 필요',
        accidentPrecautions: null,
        facilities: null,
        furnishedItems: null,
        purchasableItems: null,
        rentableItems: null,
        additionalInformation: null,
      },
      galleryImages: [{
        name: '매장 전경',
        originalUrl: 'https://example.com/gallery.jpg',
        thumbnailUrl: null,
        copyrightType: null,
      }],
      amenities: ['물그릇', '야외 좌석'],
    }
  },
}
